DTS-STN/future-sir

future-sir-gitops/base/reloader/deployments.yaml, future-sir-gitops/base/reloader/kustomization.yaml, future-sir-gitops/base/reloader/roles.yaml, future-sir-gitops/base/reloader/service-accounts.yaml, future-sir-gitops/overlays/dev/patches/deployments.yaml, future-sir-gitops/overlays/shared/kustomization.yaml, future-sir-gitops/overlays/shared/patches/stateful-sets.yaml
Add Stakater Reloader to monitor ESO secrets and restart the pods whenever the secrets change.
- <https://docs.stakater.com/reloader/>
=> gitops: add stakater reloader

future-sir-frontend/app/routes/auth/callback.tsx, future-sir-frontend/app/routes/auth/login.tsx, future-sir-frontend/app/utils/auth/authentication-strategy.ts, future-sir-frontend/app/utils/auth/azuread-authentication-strategy.ts, future-sir-frontend/app/utils/auth/local-authentication-strategy.ts, future-sir-frontend/tests/utils/auth/authentication-strategy.test.ts
Being explicit about the auth strategy name since minification/transpilation can change the value of `constructor.name`.
=> refactor: remove `constructor.name` from auth strategy base class

future-sir-frontend/app/.server/express/session.ts
There's a bug in express-session's memory session.. the cookie.expires attribute is serialized to a string during `set()`, but not deserialized during `get()` (despite the ts types saying it should be).
=> fix: broken date comparison in memory session store

frontend/app/components/app-link.tsx, frontend/app/errors/coded-error.ts, frontend/app/errors/error-codes.ts, frontend/app/i18n-config.server.ts, frontend/app/routes/auth/callback.tsx, frontend/app/routes/auth/login.tsx, frontend/app/routes/dev/error.tsx, frontend/app/utils/route-utils.ts, frontend/app/utils/validation-utils.ts, frontend/tests/components/app-link.test.tsx, frontend/tests/utils/route-utils.test.ts
- make sure all throws in the application are using `CodedError`
- centralize `ErrorCodes` to make it easier to enforce unique error codes
=> fix(frontend): use `CodedError` everywhere

frontend/tsconfig.json, frontend/vite.config.ts, frontend/vitest.workspace.ts
The `environmentMatchGlobs` configuration option has been deprecated in Vite v6.x in favor of project workspaces. This PR creates two new vitest workspaces, `jsdom` and `node` that mimics the previously configured behavior.
- <https://main.vitest.dev/config/#environmentmatchglobs>
- <https://vitest.dev/guide/workspace>
=> fix(frontend): fix vitest deprecation warning

frontend/package-lock.json, frontend/package.json
Use the WASM build [@rollup/wasm-node](https://www.npmjs.com/package/@rollup/wasm-node) instead of the native build with [Vite](https://vite.dev/).
> Rollup now includes native code that is automatically installed (and removed) as an [optional npm dependency](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies) if your platform and architecture is supported. More precisely, Rollup has a list of optionalDependencies, each of which only install on a specific [os](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os) and [cpu](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#cpu). If your system is not supported, you will receive an error message when starting Rollup that will tell you about your platform and architecture and gives you a list …
=> fix(frontend): vite dependency rollup issue

gitops/base/redis/stateful-sets.yaml
Fix misconfigured (but accidentally working 😅) redis startup args.
=> fix(gitops): fix misconfigured redis args

frontend/app/.server/environment/telemetry.ts
While integrating with Dynatrace, I discovered that the default service name in `app/.server/environment/telemetry.ts` causes a 400 response from the Dynatrace API.
=> fix(frontend): fix otel config

gitops/base/future-sir-frontend/configs/config.conf, gitops/overlays/dev/configs/future-sir-frontend/config.conf, gitops/overlays/dev/external-secrets.yaml
Depends on #78
Add Dynatrace OpenTelemetry configuration to gitops manifests. Note that this is mostly working, but some further configuration needs to be done in the frontend `containerfile` to get some of the OTel metadata to be correctly reported.
Note that I also updated the base config template to match the latest `.env.example` file.
=> feat(gitops): add otel configuration

frontend/app/components/dropdown-menu.tsx
Fixes the following error when building.
```
app/components/dropdown-menu.tsx (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
```
@Dario-Au `'use client';` directive copied from [shadcn/ui](https://ui.shadcn.com/) works with Next.js and not with React Router. I didn't caught that when I reviewed your PR.
https://nextjs.org/docs/app/api-reference/directives/use-client
=> fix(frontend): Error when using sourcemap for reporting an error

frontend/app/.server/express/server.ts, frontend/app/.server/logging.ts
This PR fixes the following warning that is printed during application startup:
```
(node:1166207) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
at genericNodeError (node:internal/errors:983:15)
at wrappedFn (node:internal/errors:537:14)
at _addListener (node:events:598:17)
at process.addListener (node:events:616:10)
at ExceptionHandler.handle (/home/gbaker/Projects/github/dts-stn/future-sir/frontend/node_modules/winston/lib/winston/exception-handler.js:51:15)
at DerivedLogger.add (/home/gbaker/Projects/github/dts-stn/future-sir/frontend/node_modules/winston/lib/winston/logger.js:368:23)
at …
```
=> fix(frondend): fix "possible EventEmitter memory leak detected"

frontend/app/entry.server.tsx
A bad `getLogger()` line in `entry.server.tsx` was throwing, causing all errors to be misreported in the logging console.
**Before:**
```
2025-01-15T11:46:46.705Z   ERROR --- […rver/express/handlers.ts]: Unexpected error caught by express server Cannot read properties of undefined (reading 'getLogger') --- {
stack: "TypeError: Cannot read properties of undefined (reading 'getLogger')\n" +
'    at handleError (/home/gbaker/Projects/github/dts-stn/future-sir/frontend/app/entry.server.tsx:64:37)\n' +
...
```
**After:**
```
2025-01-15T11:47:04.449Z   ERROR --- [     app/entry.server.tsx]: Uncaught error while handling request: --- {
name: 'AppError',
errorCode: 'RTE-0001',
correlationId: 'J4-GX3W29',
httpStatusCode: 500,
msg: 'No route found for /en/public/wizard/ (this should never happen)', …
```
=> fix(frontend): fix broken `entry.server.tsx` error handler

frontend/app/.server/express/middleware.ts
Recent changes to the page html has caused the express-level 500 page to break. This page is rendered whenever React Router throws outside of its error boundary.
**Before:**
**After:**
=> fix(frontend): fix broken express 500 page

frontend/app/components/input-error.tsx, frontend/app/components/input-field.tsx, frontend/app/components/input-help.tsx, frontend/app/components/input-label.tsx
Add components for the Textbox field
=> components for Text field

frontend/.vscode/settings.json, frontend/app/.server/validation/email-address-schema.ts, frontend/app/.server/validation/first-name-schema.ts, frontend/app/.server/validation/index.ts, frontend/app/.server/validation/last-name-schema.ts, frontend/app/.server/validation/name-schema.ts, frontend/app/.server/validation/string-schema.ts, frontend/app/@types/global.d.ts, frontend/app/utils/zod-utils.ts, frontend/package-lock.json, frontend/package.json, frontend/tests/.server/validation/email-schema.test.ts, frontend/tests/.server/validation/first-name-schema.test.ts, frontend/tests/.server/validation/last-name-schema.test.ts, frontend/tests/.server/validation/name-schema.test.ts, frontend/tests/.server/validation/string-schema.test.ts, frontend/tsconfig.json, frontend/vite.config.ts
This commit introduces a robust string validation schema, `stringSchema`, along with new validation schemas for first name, last name, and email address. These schemas leverage Zod for type safety and offer customizable options including:
- **String Length Validation:** Enforce minimum and maximum string lengths.
- **Format Validation:** Predefined formats (`alpha-only`, `alphanumeric`, `digit-only`, `non-digit`) and custom regular expression support.
- **Trimming:** Automatic trimming of leading/trailing whitespace (configurable).
- **Customizable Error Messages:** Tailor error messages for each validation rule.
- **100% Test Coverage:** Comprehensive unit tests ensure the reliability and correctness of the validation logic, covering all features and edge cases.
The new schemas …
=> feat(frontend): reusable validation schema

frontend/app/.server/express/middleware.ts
This pull request removes the `maxAge` attribute from the session cookie. This change addresses an issue identified in [DTS-STN/canadian-dental-care-plan](https://github.com/DTS-STN/canadian-dental-care-plan) where setting `maxAge` can cause the cookie to be prematurely removed.
=> fix(frontend): remove `maxAge` from session cookie

frontend/app/routes/protected/person-case/first-name.tsx, frontend/app/routes/protected/person-case/last-name.tsx
Updated the first name screen, upon successful validation, save the input in the session object and redirect the user to "last-name" screen.
When the screen loads, attempt to retrieve the default value for the First Name text field from the session.
First Name is loaded from session:
=> first name screen

frontend/app/components/language-switcher.tsx
This PR adds a fix to the `<LanguageSwitcher>` component that ensures querystring params are persisted across language toggles.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix(frontend): persist search params across language toggle

frontend/app/hooks/use-tab-id.ts, frontend/tests/hooks/use-tab-id.test.tsx
Add a `useTabId()` hook that can be used isolate session data per-tab/window.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Here is a small video of the tab id being generated and then added to the URL (so it can be used server-side).
[Screencast from 2025-01-30 …
=> feat(frontend): add `useTabId()` hook

frontend/app/routes/protected/in-person/state-machine.ts, frontend/package-lock.json, frontend/package.json, frontend/tests/routes/protected/in-person/state-machine.test.ts
This PR adds XState to the project and configures a very simple state machine that can navigate from one state to another when `next`, `prev`, and `cancel` events are emitted.
The flow logic follows <https://www.figma.com/design/eFeAwkp1LCalkB5q7CZxaV/FSIR> and more functionality will be added in future PRs.
<details>
``` shell
```
</details>
<details>
``` shell
npm run …
```
=> feat(frontend): add XState and initial FSM+tests

frontend/app/hooks/use-tab-id.ts
The option `{ replace: true }` should be set during navigation in the `useTabId()` hook to ensure that we don't break back/forward browser buttons. Without `{ replace: true }`, it is difficult to navigate back to the previous page because the application  will immediately navigate forward again.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
npm run …
```
=> fix(frontend): set `replace: true` in `useTabId()` hook navigation

frontend/app/errors/error-codes.ts, frontend/app/routes/protected/in-person/birth-info.tsx, frontend/app/routes/protected/in-person/contact-info.tsx, frontend/app/routes/protected/in-person/index.tsx, frontend/app/routes/protected/in-person/name-info.tsx, frontend/app/routes/protected/in-person/parent-info.tsx, frontend/app/routes/protected/in-person/personal-info.tsx, frontend/app/routes/protected/in-person/previous-sin-info.tsx, frontend/app/routes/protected/in-person/primary-docs.tsx, frontend/app/routes/protected/in-person/privacy-statement.tsx, frontend/app/routes/protected/in-person/request-details.tsx, frontend/app/routes/protected/in-person/review.tsx, frontend/app/routes/protected/in-person/secondary-docs.tsx, frontend/app/routes/protected/in-person/state-machine-service.server.ts, frontend/app/routes/protected/in-person/state-machine-service.ts, frontend/app/routes/protected/in-person/state-machine.server.ts, frontend/app/routes/protected/in-person/state-machine.ts, frontend/app/routes/protected/in-person/types.d.ts, frontend/tests/routes/protected/in-person/state-machine.test.ts
[AB#15081](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/15081) -- Explore XState for managing wizard screen flow
Refactoring to how the xstate stuff works.
- Allowing for target-state loading when hitting a route. This prevents the state machine from desynchronizing with the application URL. When you hit `/my-route` then the correct state for `my-route` is loaded.
- Moving some repeated code into helper functions.
- Strict-typing the state names to ensure some of the helper functions are called correctly.
*(check all …
=> fix(frontend): improve xstate navigation

frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/@types/express-session.d.ts, frontend/app/routes/protected/person-case/primary-docs.tsx
Work item: [#14682](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/14682)
Add document type field on primary identification screen
User is presented with the Current Status options. Based on the correct options "Canadian citizen born outside Canada" or "Registered Indian born in Canada" in current status, the document type show respective options.
On pressing next button, field is validated. Correct validation for proof of concept is "Canadian citizen born outside Canada"
The document type is validated for null value.
*(check all that apply by placing …
=> (frontend): add document type field on primary identification screen

frontend/package-lock.json, frontend/package.json
```
@vitest/coverage-v8                 ^3.0.5  →   ^3.0.6
effect                             ^3.13.1  →  ^3.13.2
eslint-import-resolver-typescript   ^3.8.1  →   ^3.8.2
react-i18next                      ^15.4.0  →  ^15.4.1
vitest                              ^3.0.5  →   ^3.0.6
```
I had to apply the following overrides for `eslint-import-resolver-typescript`, otherwise, the ESLint check fails because it can't resolve module paths with aliases. I'll open an issue for the `eslint-import-resolver-typescript` package.
```
{
...
"overrides": {
...
"eslint-import-resolver-typescript": {
"tinyglobby": "npm:tinyglobby@0.2.10"
}
}
}
```
=> chore(frontend): bump deps

frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx
If a user keyboard navigates and clicks enter to submit the form, the back button action is called (because it precedes the next button in the form and is subsequently called first).  This PR reverses the button order so that the next button is called first on form submission using a keyboard, while maintaining visual order and proper tab order for accessibility purposes. 
=> change order of form buttons in person-case routes

frontend/app/utils/date-utils.ts, frontend/tests/utils/date-utils.test.ts
This PR adds an `isValidTimeZone()` function to `app/utils/date-utils.ts` so it can be used in an up coming PR.
=> feat(frontend): add `isValidTimeZone()` function

frontend/.env.example, frontend/app/.server/environment/server.ts
This PR adds a `BASE_TIMEZONE` configuration option that will eventually be used when performing date (without timestamp) calculations in the application.
=> feat(frontend): add `BASE_TIMEZONE` envar

frontend/app/.server/resources/countries.json, frontend/app/.server/services/locale-data-service.ts, frontend/app/routes/protected/person-case/contact-information.tsx
This PR aims to add PP country data which will be consumed by the frontend to display in a select input.  Currently this data is copy/paste from CDCP.  This PR also adds a 'service' layer for fetching localized country data (with the intention of having additional functions for other PP data).  I tried to implement the simplest approach, but I'm unsure how this would scale.  One potential drawback is that the data is fetched in the loader and the action (and the action really only needs the country IDs for validation purposes).  Let me know if it's a better approach to fetch all of the countries at the top level of form file, then get a localized list in the loader, or another approach that you think is more suitable for this problem. 
*(check …
=> add countries.json and service to fetch localized countries

frontend/.env.example, frontend/app/.server/environment/client.ts, frontend/app/.server/express/server.ts
This PR enhances DX and OX by emitting the current runtime config at startup.
It also removes the default value from `I18NEXT_DEBUG` to reduce the amount of data being sent to the client (setting this to `undefined` is functionally equivalent).
=> feat(frontend): emit runtime config at startup

frontend/app/.server/environment/authentication.ts, frontend/app/.server/environment/redis.ts, frontend/app/.server/environment/session.ts, frontend/app/.server/environment/telemetry.ts, frontend/app/.server/express/middleware.ts, frontend/app/.server/opentelemetry.ts, frontend/app/.server/redis.ts, frontend/app/.server/utils/security-utils.ts, frontend/app/routes/api/health.ts, frontend/app/routes/auth/callback.tsx, frontend/app/routes/auth/login.tsx, frontend/package-lock.json, frontend/package.json, frontend/tests/.server/opentelemetry.test.ts, frontend/tests/.server/redis.test.ts, frontend/tests/.server/utils/security-utils.test.ts
This PR introduces a new `Redacted()` callable class, inspired by [effect-ts's feature of the same name](https://effect.website/docs/data-types/redacted/).
=> feat(frontend): implement a `Redacted()` feature

frontend/app/i18n-config.server.ts, frontend/app/routes/protected/admin.tsx, frontend/app/routes/protected/index.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/request.tsx, frontend/app/routes/public/index.tsx
This PR introduces a new `getTranslation()` function, which provides functionality similar to react-i18next's `useTranslation()` hook, but for server-side usage.
In various server-side parts of the codebase, we often need both the current language and a `TFunction` for translations. Previously, this required two separate function calls. With `getTranslation()`, developers can retrieve both in a single call, simplifying localization logic.
=> feat(frontend): add `getTranslation()` function

frontend/app/i18n-routes.ts
Add some LLM-generated JSDoc to `i18n-routes.ts` for an improved DX.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
When I pasted the `i18n-routes.ts` file into Google Gemini, it told me that the `Filter` template parameter used in `ExtractI18nRouteFiles` wasn't being used, so I removed it. Everything appears to function …
=> chore(frontend): enhance JSDoc in `i18n-routes.ts`

frontend/app/@types/express-session.d.ts, frontend/app/routes/protected/person-case/@types.d.ts
This PR moves the in-person session types into a localized `@types.d.ts` file in the `routes/in-person/` folder.
The global `@types/express-session.d.ts` file was intended to be used to define more application-wide session types (for example, if the user is authenticated). Polluting this file with route-specific session types will make it difficult to manage over time, because deprecated and unused types might be left to rot.
By moving the route-specific types into the `app/routes/` folder, it makes managing these types a little easier.
*(check all that …
=> refactor(frontend): move person-case session types

frontend/app/utils/date-utils.ts
There is error when next button is click on primary document screen. The fields are hidden, and would be displayed depending on the selection. Since, there is no input for the date fields yet, the 'RangeError: Invalid time value\n' error is thrown by formatISO.
This pr fix the error, by providing empty string if the input isn't available yet. 
<details>
``` shell
```
</details>
<details>
<summary>Unit and e2e …
=> bugfix(frontend): fix error on primary document screen when no date is provided

frontend/.env.example, frontend/app/.server/environment/telemetry.ts, frontend/app/.server/opentelemetry.ts, frontend/app/.server/utils/instrumentation-utils.ts, frontend/app/entry.server.tsx, frontend/tests/.server/opentelemetry.test.ts
This PR adds a `createCounter()` function to `instrumentation-utils` and creates a `server.errors.total` counter in `entry.server.tsx` to keep track of server side errors.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
I intentionally threw a few errors locally and pushed the metrics to Dynatrace to generate this graph:
=> feat(frontend): opentelemetry enhancements

frontend/.env.example, frontend/app/.server/environment/power-platform.ts, frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/.server/services/locale-data-service.ts, frontend/app/routes/protected/person-case/contact-information.tsx
adds:
- conditional rendering to display province/territory select input if country select is Canada, otherwise display an input field for user to enter their province/territory/state
- beefed up validation to handle the case where Canada is selected (validates province/territory is valid)
- modifies `locale-data-service/ts` since we only consider Canadian provinces/territories, and not US states
<details>
``` shell
npm run …
```
=> add conditional rednering and beefed up validation to /contact-information

frontend/app/.server/resources/genders.json, frontend/app/.server/services/locale-data-service.ts, frontend/app/routes/protected/person-case/primary-docs.tsx
Similar to previous PRs addressing adding PP data, this PR does the same for gender data and adds the implementation to `/primary-documents`.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> load gender.json from PP and add locale service functions

gitops/overlays/dev/configs/future-sir-frontend/config.conf
This PR re-synchronizes the gitops `overlays/dev/configs/future-sir-frontend/config.conf` with the frontend's `.env.example` file so that we can more easily trace divergent changes.
=> refactor(gitops): synchronize gitops frontend `config.conf` file

frontend/app/utils/route-utils.ts, frontend/tests/hooks/use-route.test.ts
This PR fixes a bug in `findRouteByPath()` that prevents routes with path parameters (ie: `/en/:id`) from being returned.
Once this PR is merged, I will submit a subsequent PR that updates the language switcher to retain path parameters during a language switch.
=> fix(frontend): match i18n routes containing path params

frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/utils/date-utils.ts
The error is thrown when the next button is clicked on primary document screen, without selecting any option in the select field "Current status in Canada". 
Error Description: 'RangeError: Invalid time value\n' error is thrown by formatISO.
Updated the the date utils, so that the error thrown by the formatISO isn't masked. 
Updated the primary document screen, to handle the date of birth and certification date when these values are unavailable (because these fields are hidden).
<details> …
=> refactor(frontend): update date utils

frontend/app/.server/services/locale-data-service.ts, frontend/app/routes/protected/person-case/birth-details.tsx
[AB#18177](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18177)
Refactors `/birth-details` to use PP province data when the selected country of birth is Canada.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide …
=> refactor province input in /birth-details

frontend/app/components/language-switcher.tsx, frontend/tests/components/__snapshots__/language-switcher.test.tsx.snap, frontend/tests/components/language-switcher.test.tsx
Correctly handle path parameters when language switching. Prior to this PR, any path params (ex: the `id` in `/en/:id/foo`) would get discarded, leading to a 404.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix(frontend): correctly propagate path params in `<LanguageSwitcher>`

frontend/app/errors/error-codes.ts, frontend/app/i18n-config.server.ts
As stated in the title, an AppError will be thrown if an i18next key is missing.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> feat(frontend): throw  i18next missing key error

frontend/tsconfig.json, frontend/vite.config.ts
This PR bumps the source version of ecmascript up to `ESNext` to allow developers to use the latest JS syntax in their code. See <https://developer.mozilla.org/en-US/docs/Web/JavaScript/JavaScript_technologies_overview>.
=> fix(frontend): bump ecmascript version on server to `ESNext`

frontend/app/errors/error-codes.ts, frontend/app/i18n-routes.ts, frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/layout.tsx, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/personal-info.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/review.tsx, frontend/app/routes/protected/person-case/search-sin.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx
This PR lays the groundwork for a state machine managing the in-person application flows by introducing `tabId` tracking. This feature will eventually allow users to initiate and complete multiple flows concurrently in separate browser tabs without session data conflicts.
Currently, session data is shared across all browser tabs, which prevents users from completing multiple in-person application flows concurrently.
To allow users to complete multiple in-person application flows concurrently, we need a way to isolate the data that is stored in session for each browser tab. The best way to handle this is to leverage the browser's built-in session store feature to store a unique id, which is then added to all requests in the flow.
- Ensure the `tabId` is propagated throughout the relevant …
=> feat(frontend): generate a browser tabid per flow

frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/review.tsx
[AB#14685](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/14685)
---- Add secondary docs and current name information on review screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. …
=> feat(frontend): display secondary docs and current name info on review screen

frontend/.env.example, frontend/app/.server/environment/power-platform.ts, frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/review.tsx
[AB#14685](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/14685)
---- Add personal detail and birth detail on review screen
updated country code to match IDs from PP
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and …
=> feat(frontend): add personal details and birth details on review page

frontend/package-lock.json, frontend/package.json
Fixing the following warning that appeared after merging #318:
```
npm warn deprecated @types/eslint__eslintrc@3.3.0: This is a stub types definition. @eslint/eslintrc provides its own type definitions, so you do not need this installed.
```
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix(frontend): remove deprecated package

frontend/app/routes/protected/person-case/personal-info.tsx
[AB#16170](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/16170)
Display the default values for last name at birth and gender on the personal detail screen from primary doc screen data
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> update(frontend): fix the personal detail screen to display primary doc screen data

frontend/app/hooks/use-tab-id.ts, frontend/app/routes/protected/person-case/@types.d.ts, frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/layout.tsx, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/personal-info.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/review.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx
[AB#15081](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/15081) -- *explore XState for managing wizard screen flow*
This PR adds browser-tab data isolation for the in-person application.
It manages this by storing the data for each flow in an isolated session slot which is indexed by a `tid` (tab id) search param (ex: `context.session.inPersonSinApplications[tabId]`).
The `tid` is auto-generated and added to the URL on demand as needed.
=> feat(frontend): in-person browser tab isolation

frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/components/address.tsx, frontend/app/routes/protected/person-case/review.tsx, frontend/app/utils/string-utils.ts, frontend/tests/utils/string-utils.test.ts
[AB#14685](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/14685)
Add details for parents, sin and contact information on review page
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Information for parents is available on review screen:
Parents information is unavailable, Previous sin and …
=> feat(frontend): add details for parents, sin and contact information on review page

frontend/app/routes/protected/person-case/personal-info.tsx
[AB16170](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/16170)
Fix the bug: If the Fields "Other first name previously used" and "Other last name previously used" are empty and "Next" button is clicked, an empty string was added in other names field on personal detail screen..
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
``` …
=> update(frontend): fix adding empty string in other names field on personal details screen

frontend/app/.server/environment/client.ts, frontend/app/.server/environment/server.ts
This PR moves the `BASE_TIMEZONE` config value to client-side.
=> fix(frontend): move `BASE_TIMEZONE` to client config

frontend/app/components/date-picker-field.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx, frontend/app/routes/protected/person-case/state-machine.ts
[AB#18744](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18744) Update Secondary screen
- Remove expiry day  (should only be month / year)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> feat(frontend): Update secondary screen

frontend/app/routes/protected/person-case/contact-information.tsx
Previously, if a user were to submit the form without selecting a country, the validation errors for hidden inputs would be sent back to the client.  This PR fixes that issue.
=> fix validation schema in /contact-information

gitops/overlays/dev/configs/future-sir-frontend/config.conf, gitops/overlays/dev/external-secrets.yaml
De-integrate the dev pseudoenvironment with Azure AD, since we now have a dedicated int environment for integration testing.
=> refactor(gitops): de-integrate dev w/ Azure AD

frontend/app/routes/protected/person-case/contact-information.tsx
Previously if a user were to enter a valid phone number, submit the form without error, and navigate back to `/contact-information`, the phone number would not be rendered to the client.  A console error reveals that the phone number isn't formatted as an E.164 number.  This PR addresses that issue by adding a transform to leverage `libphonenumber-js` and strip any subsequent white space.
<details>
``` shell …
```
=> add phone number transform to validation schema

frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/routes/protected/person-case/personal-info.tsx
[AB16170](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/16170l)
On Personal detail screen, added validations on the following fields when Add name button is pressed. Both client side and server side validations are added.
Fields:
Other first names previously used
Other last names previously used 
Validation:
for max character length of 100, and names should not contain digits
<details>
``` shell
``` …
=> update(frontend): validation for other names on personal detail screen

frontend/app/.server/express/middleware.ts, frontend/app/.server/express/server.ts
ZAProxy was complaining about missing security headers for some requests. To fix this, I moved the security middleware higher up in the call stack to ensure that it gets triggered for all requests.
=> fix(frontend): apply security response headers to all requests

frontend/app/components/card.tsx
Github copilot is suggesting that using `ComponentProps<'...'>` is a more idiomatic way to define the types for intrinsic html elements when using react.
=> refactor(frontend): update types in `card.tsx`

infrastructure/terragrunt/nonprod/frontend-service-principal/terragrunt.hcl
"CC" (name redacted) on the power-platform team requires our app registration (oauth client) to be temporarily public. We can remove this setting once he is finished his R&D work.
=> fix(infra): make oauth client public

frontend/app/routes/protected/person-case/abandon.tsx, frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/layout.tsx, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/personal-info.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/review.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx, frontend/app/routes/protected/person-case/state-machine.ts, frontend/app/routes/protected/person-case/types.d.ts
There is an issue with resetting the xstate context when sending the 'cancel' event. This PR fixes that issue, and moves some of the types to `types.d.ts`.
=> fix(frontend): fix bug with xstate init/re-init

frontend/app/routes/protected/person-case/abandon.tsx, frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/personal-info.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/review.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx
On main branch, there is typescript error when you run npm run checks, this pr fix this error.
Error:
Property 'context' is missing in type '{ params: { [key: string]: string | undefined; }; request: Request; }' but required in type 'ActionFunctionArgs<any>'.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR …
=> refactor(frontend): fix the typescript error on getStateRoute

frontend/.env.example, frontend/app/.server/environment/interop-api.ts, frontend/app/.server/shared/api/interop-client-config.ts
Since there can eventually be more than one interop API, I've renamed the existing one for clarity.
=> refactor(frontend): rename Interop API environment variables for clarity

frontend/app/routes/protected/person-case/types.d.ts
The type definitions for `BirthDetailsData` and `ParentDetailsData` were incorrect.
=> fix(frontend): fix type definitions for `BirthDetailsData` and `ParentDetailsData`

gitops/overlays/dev/configs/future-sir-frontend/config.conf
Trivial PR to sync dev config with .env.example (to make it easier to diff).
=> chore(gitops): sync dev config ↔ .env.example

frontend/app/routes/protected/person-case/review.tsx
[AB1485](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/14685)
display localized SIN options on review page.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> refactor(frontend): display localized SIN options on review page

frontend/app/.server/resources/esdc_applicantstatusincanada.json, frontend/scripts/fetch-power-platform-data.ts
As per title, adding `esdc_applicantstatusincanada` missing code table JSON from Power Platform.
=> feat(frontend: add esdc_applicantstatusincanada code table JSON

frontend/app/routes/protected/multi-channel/finalize-request.tsx
[AB19138](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19138) Update Finalize screen to auto-select office's province code
- Modified finalize screen to automatically select the province.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any …
=> feat(frontend): Update finalize screen with province auto-select

frontend/app/routes/protected/person-case/primary-docs.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/state-machine.server.ts, frontend/app/routes/protected/person-case/types.d.ts
Refactor the form persistence code:
- Rename `rawDataMap` to `formData` to be more descriptive (I think)
- Re-type the form data to be a little more lenient
- Move form data reset calls into machine actions
- Refactor loaders/actions/components to use `loaderData.formValues` and `loaderData.formErrors` (instead of `defaultFormValues`, etc)
=> refactor(frontend): change how the form data+errors persist

frontend/app/routes/protected/person-case/layout.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/state-machine.server.ts
Adds a previous button to the privacy statement screen.  This requires modifying the state machine to handle an exit action which should reset the context and also remove the `tid` from the search param upon navigating back to the index screen.
Also updated the style of the spinner in the layout, but honestly the styling isn't really that bad to being with so this is just a shoehorn to remove a todo.
<details>
``` shell
npm run …
```
=> add previous button to privacy statement

frontend/app/components/error-boundaries.tsx, frontend/app/components/lists.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/sin-application.tsx, frontend/tests/components/__snapshots__/error-boundaries.test.tsx.snap, frontend/tests/components/__snapshots__/lists.test.tsx.snap, frontend/tests/components/lists.test.tsx
Add `OrderdList` and `UnorderedList` reusable components to stream line lists base style in the application.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> feat(frontend): add reusable list components

frontend/app/entry.server.tsx, frontend/containerfile
- fix the image name in `containerfile` (this name is also used for the OpenTelemetry `service.name` dimension)
- fix the error counter's dimensions to fit more with standard dimension naming conventions
=> chore(frontend): otel tweaks

frontend/app/.server/domain/person-case/models.ts, frontend/app/.server/domain/person-case/services/applicant-primary-document-service.ts, frontend/app/.server/resources/fsir_applicantprimarydocumentchoices.json
Add a custom FSIR data resource: fsir_applicantprimarydocumentchoices.json. The existing esdc_applicantprimarydocumentchoices.json does not meet the needs of this POC, so we've opted to create a tailored resource instead.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain …
=> refactor(frontend): add custom fsir data source for primary document choices

frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/routes/protected/multi-channel/pid-verification.tsx
Breaks out the validation status message on `/multi-channel/pid-verification` into separate components for conditional rendering based on the validation status sent back from the server upon "sending for validation" on the previous page.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant …
=> split out validation status messages into components on /pid-verfication

frontend/app/.server/auth/auth-strategies.ts, frontend/tests/auth/auth-strategies.test.ts
This is an incremental PR that will ultimately finish with full integration with AWS Cognito.
This PR adds a new authentication strategy, `AwsCognitoAuthenticationStrategy` to `app/.server/auth/auth-strategies.ts` (currently unused).
=> feat(frontend): add AWS Cognito authentication strategy

frontend/app/.server/locales/gcweb-en.json, frontend/app/.server/locales/gcweb-fr.json, frontend/app/.server/locales/protected-en.json, frontend/app/.server/locales/protected-fr.json, frontend/app/components/links.tsx, frontend/app/routes/protected/multi-channel/finalize-request.tsx
Similar to cdcp, this PR adds a `NewTabIndicator` component which is used for app-links that open in a new tab.  It adds screenreader accessible text to those links.  This PR implements the new functionality on `/multi-channel/finalize-request` as I noticed Figma was updated with a link to an external resource in one of the paragraphs.
<details>
``` shell
```
</details>
<details>
<summary>Unit and e2e …
=> add newTabIndicator to link components

frontend/app/routes/protected/person-case/primary-docs.tsx
Refactor the primary documents to use controlled select inputs for the `Current status in Canada` and `Document type` fields. Additionally, update the form and input styles.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context …
=> refactor(frontend): primary docs controlled inputs

frontend/app/.server/environment/server.ts
This PR adds a temporary environment variable to hold an AWS identity token. This token will be propagated to a downstream API to assert the identity of the logged in user.
Note that a default token has been provided. This token contains placeholder data and, more importantly, cannot be validated by any downstream APIs. The default token is intended to be used simply as a placeholder when running the application locally.
=> feat(server): add temporary AWS ID token validation for development

frontend/app/@types/express-session.d.ts, frontend/app/routes/protected/person-case/review.tsx
From my understanding, for the purpose of the demo, we want to access created cases in session.  This PR adds a new entry in the session for created cases.  There might be some overlap with types, and some tweaking might be necessary.  
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant …
=> add created case to session

gitops/overlays/int/external-secrets.yaml
Add a new ID token to ESO in int. Value has already been added to the vault.
=> chore(gitops): add temporary AWS ID token configuration for March demo

frontend/app/.server/domain/multi-channel/case-api-service-default.ts, frontend/app/.server/domain/multi-channel/case-api-service.ts, frontend/app/routes/protected/multi-channel/send-validation.tsx
The sin-validation page would throw a 500 when the id was not found.. this goes back to the service module throwing when no data is found instead of returning undefined 
The API calls can return 404 but our service should return undefined instead of throwing error
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR …
=> refactor(frontend): service return undefined instead of throwing error

frontend/app/.server/domain/sin-application/sin-application-models.ts, frontend/app/.server/domain/sin-application/sin-application-service-mock.ts, frontend/app/routes/protected/person-case/review.tsx, frontend/app/routes/protected/person-case/state-machine.server.ts, frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts, frontend/tests/.server/domain/sin-application/sin-application-service-mock.test.ts
Update in-person submission logic to store the data in the mock store and then link to the multi-channel flow. (see attached video)
**Important:** this code will have eventually have to be removed and replaced with proper handling in the state machine.
[Screencast from 2025-03-26 08-57-02.webm](https://github.com/user-attachments/assets/8289060d-bdfb-45a5-8895-20316ab9f844)
=> feat(frontend): update submission logic

gitops/overlays/int/external-secrets.yaml
Reducing the TTL for the ESO secrets down to 5m since we want a quick update after modifying the vault values.
=> fix(gitops): reduce refresh interval for external secrets from 1h to 5m

frontend/app/i18n-routes.ts, frontend/app/routes/protected/multi-channel/finalize-request.tsx, frontend/app/routes/protected/multi-channel/pid-verification.tsx, frontend/app/routes/protected/multi-channel/search-sin.tsx, frontend/app/routes/protected/multi-channel/send-validation.tsx
update multichannel route to include case Id parameter
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or …
=> refactor(frontend): update multichannel route to include case Id parameter

frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
[AB#19772](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19772)
Redirect to protected dashboard after multi-channel flow completion.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> refactor(frontend): redirect to protected dashboard after multi-channel flow completion

frontend/app/.server/domain/sin-application/sin-application-mappers.ts, frontend/app/.server/domain/sin-application/sin-application-models.ts, frontend/app/.server/domain/sin-application/sin-application-service-default.ts, frontend/app/routes/protected/person-case/review.tsx
([AB#19766](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19766) -- ensure successfully submitted person-case is stored in sin cases store)
This PR adds code to store the a SIN application to the temporary sin-cases-store after successful submit.
=> fix(frontend): add submitted application to store after API call

frontend/.env.example
=> fix(frontend): fix typos in .env.example

frontend/app/routes/protected/person-case/review.tsx
([AB#19767](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19767) -- ensure person-case is destroyed after submission)
Kill the state machine after a successful API call. This code is not intended to stay in the application for long.. once the API call is moved to the state machine (or we remove the state machine), this code should be removed.
=> fix(frontend): add session/machine cleanup when submitting

frontend/app/.server/domain/multi-channel/sin-case-models.ts, frontend/app/.server/domain/sin-application/sin-application-models.ts, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/state-machine-models.ts, frontend/app/routes/protected/person-case/validation.server.ts, frontend/app/routes/protected/sin-application/review-parent-details.tsx
[AB#19764](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19764)
Country field in the Parent/Legal Details route should be optional as per Figma. Updated validation to remove error on Country field. Also updated DTOs and model to indicate Country is optional.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR …
=> refactor(frontend): review country field on parent details screen

frontend/app/.server/express/server.ts, frontend/app/.server/logging.ts
Whenever a new logger is created by winston, it adds two new event listeners (one for  `uncaughtException` and one for `unhandledRejection`).
Nodejs configures `process.maxListeners` to be 10 by default, and then issues the following warning if more than the max are registered:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. XX event listeners added to [process]. MaxListeners is YY. Use emitter.setMaxListeners() to increase limit.
```
This PR simply increments `process.maxListeners` by two every time a new logger is created to accommodate the new listeners added by winston.
Before submitting this PR, ensure that you have completed the following. You …
=> fix(frontend): tweak `setMaxListeners()` call

frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
Display correct province name on sin confirmation screen instead of guid
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> refactor(frontend): fix province name on sin confirmation screen

frontend/.env.example
The `.env.example` file was missing `ENABLE_SIN_SEARCH_SERVICE_MOCK`.
=> chore(frontend): add missing envar to `.env.example`

frontend/app/components/error-boundaries.tsx
Noticed this fix in <https://github.com/DTS-STN/cdb-estimator/pull/112/>. Not *really* a bug, since it rendered correctly, but should be fixed all the same.
=> fix(frontend): fix minor `BilingualNotFound` i18n bug

frontend/app/routes/protected/person-case/birth-details.tsx, frontend/app/routes/protected/person-case/contact-information.tsx, frontend/app/routes/protected/person-case/current-name.tsx, frontend/app/routes/protected/person-case/parent-details.tsx, frontend/app/routes/protected/person-case/personal-info.tsx, frontend/app/routes/protected/person-case/previous-sin.tsx, frontend/app/routes/protected/person-case/privacy-statement.tsx, frontend/app/routes/protected/person-case/request-details.tsx, frontend/app/routes/protected/person-case/secondary-doc.tsx, frontend/app/routes/protected/sin-application/primary-docs-form.tsx, frontend/app/utils/i18n-utils.ts, frontend/app/utils/validation-utils.ts, frontend/tests/utils/i18n-utils.test.ts, frontend/tests/utils/validation-utils.test.ts
Refactor how the valibot i18n keys are handled:
- move `getSingleKey()` to `validation-utils`
- rename `getSingleKey()` to `extractValidationKey()`
- rewrite jsdoc to better explain the purpose of this function:
```ts
/**
* Normalizes validation error messages into a single i18next `ResourceKey`.
*
* Valibot validation errors are typically arrays of strings, but i18next
* expects a single `ResourceKey`. This function extracts a key from the array
* and effectively casts it as a `ResourceKey`, allowing the result to be safely
* used with i18next while maintaining TypeScript compatibility.
*
* - If `value` is a single `ResourceKey` (ie: `string`), it is returned unchanged.
* - If `value` is an array, the element at `index` (defaulting to `0`) is returned.
* - If `value` is `undefined`, the …
```
=> refactor(frontend): replace `getSingleKey()` with `extractValidationKey()` for improved readability

frontend/app/components/data-table.tsx, frontend/app/components/table.tsx
Add table reusable components based of [Shadcn Table](https://ui.shadcn.com/docs/components/table) and [Flowbite Table](https://flowbite.com/docs/components/tables/) style. Unit tests will follow in another PR.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning …
=> feat(frontend): Add table reusable components

frontend/app/routes/protected/multi-channel/search-sin.tsx, frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
[AB#19919](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19919)
Updates the displayed names in the UI based on business requirements.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. …
=> fix(frontend) update sin card names

frontend/app/.server/auth/auth-strategies.ts
There was an unused `tracer` class field in `BaseAuthenticationStragegy`.
=> refactor(frontend): remove unused tracer field `BaseAuthenticationStrategy`

frontend/app/.server/utils/security-utils.ts
This PR modifies the `Redacted` class to output `undefined` when calling `toString()` to help improve environment variable logging.
=> fix(frontend): update `Redacted` class to return `undefined` when no initial value is provided
