DTS-STN/future-sir

- future-sir-frontend/package-lock.json
- future-sir-frontend/package.json
> Revert "chore(deps-dev): bump @trivago/prettier-plugin-sort-imports from 4.3.0 to 5.0.1 in /future-sir-frontend"

- future-sir-frontend/.env.example
- future-sir-frontend/app/.server/express/environment.ts
- future-sir-frontend/app/.server/express/middlewares.ts
- future-sir-frontend/app/.server/express/opentelemetry.ts
- future-sir-frontend/app/.server/express/sessions.ts
- future-sir-frontend/app/routes/auth/callback.tsx
- future-sir-frontend/app/routes/auth/login.tsx
- future-sir-frontend/containerfile
- future-sir-frontend/package-lock.json
- future-sir-frontend/package.json
Per title. Also using this PR to test the branch protections.
> feat: enhance telemetry

- future-sir.code-workspace
> chore: create gitops subproject

- future-sir-gitops/.gitignore
- future-sir-gitops/README.md
- future-sir-gitops/base/future-sir-frontend/configs/config.conf
- future-sir-gitops/base/future-sir-frontend/configs/secrets.conf
- future-sir-gitops/base/future-sir-frontend/deployments.yaml
- future-sir-gitops/base/future-sir-frontend/kustomization.yaml
- future-sir-gitops/base/future-sir-frontend/services.yaml
Add a base kustomize deployment to be added to later.
> chore: add base gitops configs

- future-sir-frontend/LICENSE.md
- future-sir-gitops/LICENSE.md
- future-sir-infrastructure/LICENSE.md
**Pull Request Description**
This PR adds the MIT License file to the repository, granting users the freedom to use, modify, and distribute the project's code under permissive terms.
> Add MIT license

- future-sir-gitops/base/reloader/kustomization.yaml
Trivial refactor.. just re-ordering some yaml.
> refactor: alphabetize resources

- future-sir-frontend/.vscode/extensions.json
Add recommended vscode extensions in `Frontend`
> chore(frontend): recommended vscode extensions

- future-sir-frontend/package-lock.json
- future-sir-frontend/package.json
```
@opentelemetry/sdk-trace-node  ^1.29.0  →  ^1.30.0
```
> chore(frontend): bump dependency

- future-sir-frontend/app/i18n-config.server.ts
- future-sir-frontend/app/root.tsx
- future-sir-frontend/app/utils/auth/authentication-strategy.ts
Add some logging to authentication-strategy.ts
> chore: add logging; fixup some imports

- frontend/app/routes/api/translations.ts
- frontend/app/routes/auth/callback.tsx
- frontend/app/routes/auth/login.tsx
- frontend/app/routes/auth/logout.tsx
- frontend/app/routes/dev/oidc-provider.tsx
Returning responses instead of throwing in loaders/actions. See <https://reactrouter.com/start/framework/navigating#redirect>.
> fix(frontend): return responses instead of throwing

- gitops/base/redis/stateful-sets.yaml
> fix(gitops): fix broken redis probes

- frontend/tests/.server/validation/email-schema.test.ts
- frontend/tests/.server/validation/first-name-schema.test.ts
- frontend/tests/.server/validation/last-name-schema.test.ts
- frontend/tests/.server/validation/name-schema.test.ts
- frontend/tests/.server/validation/string-schema.test.ts
> test(frontend): enhance unit tests for reusable validation schemas

- frontend/tests/.server/redis.test.ts
Add tests for `app/.server/redis.ts`. Coverage is almost 100% (the internal backoff function is not being tested).
> test(frontend): add redis tests

- frontend/tests/.server/opentelemetry.test.ts
- frontend/tests/setup.ts
Add tests for `app/.server/opentelemetry.ts`. Coverage is 100%.
> test(frontend): add opentelemetry tests

- frontend/app/.server/utils/auth-utils.ts
- frontend/app/@types/express-session.d.ts
- frontend/app/@types/global.d.ts
- frontend/app/@types/react-router.d.ts
- frontend/app/routes/auth/callback.tsx
- frontend/app/routes/auth/login.tsx
Declare `inPersonSINCase` property on express session object to store data for an in-person SIN case.
AB#14940
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> feat(frontend): add inPersonSINCase session data

- frontend/app/components/anchor-link.tsx
- frontend/app/utils/link-utils.ts
- frontend/tests/components/__snapshots__/anchor-link.test.tsx.snap
- frontend/tests/components/anchor-link.test.tsx
> frontend: add anchor link component

- frontend/containerfile
Bump node to v22.13.1 - [2025 Security Releases](https://nodejs.org/en/blog/vulnerability/january-2025-security-releases)
> build(frontend): bump node to v22.13.1

- frontend/app/components/input-checkbox.tsx
- frontend/app/components/input-checkboxes.tsx
- frontend/app/components/input-legend.tsx
- frontend/tests/components/__snapshots__/input-checkbox.test.tsx.snap
- frontend/tests/components/__snapshots__/input-checkboxes.test.tsx.snap
- frontend/tests/components/__snapshots__/input-legend.test.tsx.snap
- frontend/tests/components/input-checkbox.test.tsx
- frontend/tests/components/input-checkboxes.test.tsx
- frontend/tests/components/input-legend.test.tsx
Add UI components: Check box, Checkboxes, Legend.
> frontend: Add UI component for input checkbox

- frontend/app/components/button-icons.tsx
- frontend/tests/components/__snapshots__/button-icon.test.tsx.snap
- frontend/tests/components/button-icon.test.tsx
Provide a concise description of the changes made in this PR. Highlight the purpose, the problem being solved, or the feature being added. If applicable, link to any relevant issue(s).
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> frontend: Add UI component button icon

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/error-summary.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/index.tsx
- frontend/app/routes/protected/layout.tsx
- frontend/app/routes/protected/person-case/first-name.tsx
- frontend/app/routes/protected/person-case/last-name.tsx
- frontend/app/utils/zod-utils.ts
- frontend/tests/components/__snapshots__/error-summary.test.tsx.snap
- frontend/tests/components/error-summary.test.tsx
Added the last name screen with error validation.
> feat(frontend): last name screen

- frontend/tests/setup.ts
- frontend/vite.config.ts
Suppress logging while running tests. The existing configuration didn't work in some situations where the module being tested was loaded before vitest's `beforeEach()` function was being called.
> test(frontend): fix test logging

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/components/dialog.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/tests/components/__snapshots__/dialog.test.tsx.snap
- frontend/tests/components/dialog.test.tsx
> feat(frontend): Dialog Component

- frontend/app/components/dialog.tsx
- frontend/package.json
Fixed formatting
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> fix(frontend): fixed formatting

- .github/pull-request-template.md
Add a few useful commands to the PR template.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> chore(frontend): update pr template

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/components/date-picker-field.tsx
- frontend/app/utils/date-utils.ts
- frontend/app/utils/string-utils.ts
Add component for date picker field
> (frontend): Add component for date picker field

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/components/session-timeout.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/tests/components/session-timeout.test.tsx
Added Session-Timeout Component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> feat(frontend): Session-Timeout Component

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/.server/validation/confirmPrivacyNoticeSchema.ts
- frontend/app/@types/express-session.d.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/index.tsx
- frontend/app/routes/protected/person-case/first-name.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
add screen for privacy statement
> feat(frontend): add screen for privacy statement

- frontend/.vscode/extensions.json
Add [XState VSCode extension](https://marketplace.visualstudio.com/items?itemName=statelyai.stately-vscode) to recommended extensions list. (also sorted list alphabetically)
> feat(frontend): add xstate vscode extension

- frontend/app/routes/protected/in-person/state-machine.ts
- frontend/app/routes/protected/in-person/types.d.ts
- frontend/tests/routes/protected/in-person/state-machine.test.ts
Title. (this is an incremental PR to reduce the size of subsequent PRs)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> fix(frontend): remove unnecessary state transition; add state loader

- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/in-person/birth-info.tsx
- frontend/app/routes/protected/in-person/contact-info.tsx
- frontend/app/routes/protected/in-person/index.tsx
- frontend/app/routes/protected/in-person/layout.tsx
- frontend/app/routes/protected/in-person/name-info.tsx
- frontend/app/routes/protected/in-person/parent-info.tsx
- frontend/app/routes/protected/in-person/personal-info.tsx
- frontend/app/routes/protected/in-person/previous-sin-info.tsx
- frontend/app/routes/protected/in-person/primary-docs.tsx
- frontend/app/routes/protected/in-person/privacy-statement.tsx
- frontend/app/routes/protected/in-person/request-details.tsx
- frontend/app/routes/protected/in-person/review.tsx
- frontend/app/routes/protected/in-person/secondary-docs.tsx
- frontend/app/routes/protected/in-person/state-machine.ts
This is an incremental PR that adds some new routes to be used for the in-person flow. This is incomplete functionality, being submitted for review so that future PRs will not be as large.
~This PR depends on #167 and #168, so it will be marked as draft until those are merged.~
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
``` …
> feat(frontend): incremental commit to add xstate routes

- frontend/app/components/input-field.tsx
Remove deprecated forward ref from input field
> (frontend): remove forward ref from input field

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/primary-docs.tsx
Add new screen for primary document
> (frontend): add new screen for primary document

- frontend/package-lock.json
- frontend/package.json
```
tailwindcss   ^4.0.1  →  ^4.0.3
vite         ^6.0.11  →  ^6.1.0
vitest        ^3.0.4  →  ^3.0.5
```
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> chore(frontend): bump dependencies

- frontend/app/components/state-machine-debug.tsx
Add a simple `<StateMachineDebug>` component that can be added to routes to display the current XState machine context. Useful for troubleshooting and debugging.
([AB#15081](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/15081))
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> feat(frontend): add `<StateMachineDebug>` component

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/current-name.tsx
Added current name and supporting document screen
Work Item: [14630](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/14630)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, …
> feat(frontend): Current name and supporting document screen

- frontend/app/components/input-field.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/tests/components/__snapshots__/input-field.test.tsx.snap
Refactoring of the InputField component.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> refactor(frontend): InputField component

- .github/workflows/build-frontend.yaml
- .github/workflows/pr-checks.yaml
This is an attempt to fix future-sir's broken PR checks. Unfortunately, I don't know if it will actually work without testing it by submitting a test PR once this is merged.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> fix(repo): attempt to fix broken PR build checks

- frontend/app/components/input-file.tsx
- frontend/tests/components/__snapshots__/input-file.test.tsx.snap
- frontend/tests/components/input-file.test.tsx
Added Input File Component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> feat(frontend): Input File Component

- .github/workflows/build-frontend.yaml
- .github/workflows/pr-checks.yaml
This PR reverts #217, #216, and #213. The fixes did not work as expected.
> fix(project): revert pr-check fixes

- frontend/app/components/input-checkbox.tsx
- frontend/app/components/input-checkboxes.tsx
- frontend/app/components/links.tsx
- frontend/tests/components/__snapshots__/input-checkbox.test.tsx.snap
- frontend/tests/components/__snapshots__/input-checkboxes.test.tsx.snap
- frontend/tests/components/input-checkbox.test.tsx
- frontend/tests/components/input-checkboxes.test.tsx
Refactoring of the `InputCheckbox` and `InputCheckboxes` components.
> refactor(frontend): InputCheckbox and InputCheckboxes components

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/utils/string-utils.ts
Updated Current Name screen to match Figma
- Updated SessionData
- Added recorded name to Current Name screen
- Added different preferred name option
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend): Updated Current Name screen with name change option

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/errors/error-codes.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/utils/sin-utils.ts
- frontend/tests/utils/sin-utils.test.ts
[AB#16602](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/16602)
This PR adds:
- `/protected/person-case/previous-sin`
- `sin-utils.ts` for validating SINs using Luhn's algorithm
- unit tests for `sin-utils`
> add protected/person-case/previous-sin route

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/birth-details.tsx
Added Birth details screen
Work Item: [16027](https://dev.azure.com/ESDCCM/FSIR/_boards/board/t/DTS%20Team/Stories?workitem=16027)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend): Birth details screen

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/.server/resources/province-territory-state.json
- frontend/app/.server/services/locale-data-service.ts
- frontend/app/routes/protected/person-case/contact-information.tsx
Adds:
- `province-territory-state.json` data from PP
- service method(s) for getting province data and localized province data
- implementations in `/contact-information`
- locale cleanup
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> add province-territory-state.json and service methods

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/@types/express-session.d.ts
- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/utils/date-utils.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/tests/utils/date-utils.test.ts
work item # [14682](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/14682)
Added more fields to the Primary document screen, as displayed in figma.
On selecting these values in these fields:
Current status in Canada:  "Canadian citizen born outside Canada" (rest of the options are disabled)
Document type: "Certificate of Canadian Citizenship" (rest of the options are disabled)
More fields are displayed (and validated after input):
Registration number (8 digit number)
Client number (10 digit number)
Given name (non digit alphabets lass than 100 characters)
Last name (non digit alphabets lass than 100 characters)
Date of birth (should be a date in past or today)
Gender (options: female, male, other)
Citizenship date (should be a date)
Upload primary identification document. (File)
What …
> (frontend): primary document fields added

- frontend/app/utils/date-utils.ts
- frontend/tests/utils/date-utils.test.ts
Add some extra checks for some of the tests in `date-utils.ts`. Also did some minor formatting.
> test(frontend): increase coverage for some date-utils functions

- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/package-lock.json
- frontend/package.json
Fixed input for current name screen, as the boolean fields may be undefined.
> fix(frontend): Fix input for current name screen

- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
> refactor(frontend): code cleanup

- frontend/.env.example
Fixup and add some comments to `.env.example`
> feat(frontend): fixup comments in `.env.example`

- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
Trivial change to ensure how we put data in session the same way in each action.
> refactor(frontend): bring some .tsx files in line with others

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
[AB#16170](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/16170)
Add personal detail screen with the fields for: 
- Previously used first names: optional - array of string
- Last name at birth: required - no digit allowed, max length 100 characters
- Previously used last names: optional - array of string
- Gender: required - options - Female, Male, Other
<details>
``` shell …
```
> feat(frontend): add personal detail screen

- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
> refactor(frontend): code conventions

- frontend/app/tailwind.css
The style for disabled options in input select component are updated to differentiate between active and disabled options.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> refactor(frontend): update style on disabled options in select

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/date-picker-field.tsx
- frontend/app/components/input-file.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/app/utils/date-utils.ts
- frontend/tests/components/__snapshots__/input-file.test.tsx.snap
- Added Secondary Document screen
- Added English and French text for Secondary Document screen
- Added Secondary Document screen to routes
- Updated Session Data with Secondary Document info
- Updated routes for Current Name and Primary Docs screens
- Updated date picker component to not require a default value
- Fixed RequestDetails's default function name
- Fixed input file component
- Added English and French text for input file component 
- Updated input file to support French text
- Updated input file tests
Work Item: [15461](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/15461)
Before submitting this PR, ensure that you have completed the following. You can fill these …
> feat(frontend): Secondary Document screen

- frontend/docs/authentication.md
Add a line to `docs/authentication.md` explaining the `ENABLE_DEVMODE_OIDC` environment variable.
> docs(frontend): add line to `authentication.md`

- frontend/docs/routing.md
Add a doc providing an overview of how the i18n routing works.
> docs(frontend): add `docs/routing.md` doc

- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
work #[16170](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/16170)
Update the gender field to load data from locale data service in the personal info screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free …
> refactor(frontend): update the gender field to load data from locale data service in the personal info screen

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/.server/services/locale-data-service.ts
- frontend/app/components/language-switcher.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/utils/date-utils.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/tests/components/__snapshots__/language-switcher.test.tsx.snap
- frontend/tests/components/language-switcher.test.tsx
Added Parent Details Screen
[AB#16028](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/16028)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> feat(frontend): Parent Details Screen

- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
Fix forward/back navigation in `/person-case` flow now that the necessary route PRs have been merged.  Also fixes the keyboard navigation issue (#232) in one of the routes that didn't have the change made 
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and …
> fix navigation in /person-case flow

- frontend/app/routes/protected/person-case/current-name.tsx
- Added missing primary doc name
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help …
> fix(frontend): Added missing primary doc name

- frontend/app/routes/protected/person-case/parent-details.tsx
Fix parent details screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers …
> fix(frontend): Fix parent details screen

- frontend/app/routes/protected/person-case/parent-details.tsx
Fix eslint error on parent-info screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to …
> refactor(frontend): fix eslint error on parent info screen

- frontend/app/components/input-file.tsx
- frontend/app/routes/protected/person-case/@types.d.ts
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/tests/components/__snapshots__/input-file.test.tsx.snap
Disabled file upload fields
[AB#18528](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18528)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> fix(frontend): Disabled file upload fields

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/person-case/search-sin.tsx
[AB#18529](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18529)
Incremental PR to add the Search for a SIN route.  This PR adds structural markup as seen in figma.  I've identified todos for later PRs.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> add structural markup for search for a sin route

- frontend/app/components/data-table.tsx
- frontend/app/routes/protected/person-case/search-sin.tsx
[AB#18529](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18529)
Adds reuseable DataTable component and implementation using mock data in `/sin-search` when the user clicks the search button.  Unit tests need to be implemented, which I'll do after this PR is merged, and I'm sure there will be changes requested here. 
<details>
``` shell
```
</details>
<details>
<summary>Unit …
> add reuseable data-table component and implement in /sin-search

- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
Clean up the typecasting in dynamically-generated i18n keys.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> refactor(frontend): use better types in i18n typecasting

- frontend/app/routes/protected/person-case/contact-information.tsx
per title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the …
> add required attribute to input fields in /contact-information

- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
[AB#18529](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18529)
`/search-sin` is part of the multi-channel flow and should be moved to a new `multi-channel` folder for organization.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> move /search-sin from /person-case to /multi-channel

- frontend/openapi-ts.config.ts
> chore(frontend): add convenience link to hey-api docs

- frontend/app/routes/protected/person-case/request-details.tsx
[AB#18177](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18177)
Similar to previous PRs, this adds the implementation of the PP data service functions in `/request-details` to prepare for sending the proper IDs in the review-screen payload.  There are a few other select inputs in the app that will be addressed in future PRs.
<details>
``` shell
```
</details>
<details> …
> update /request-details to use person-case/service functions

- frontend/app/routes/protected/person-case/secondary-doc.tsx
[AB#18177](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18177)
Adds PP data service functions to `/secondary-documents` similar to previous PRs.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary …
> update /secondary-doc to use PP data service functions

- frontend/.env.example
- frontend/app/.server/environment/power-platform.ts
- frontend/app/routes/protected/person-case/previous-sin.tsx
[AB#18177](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18177)
Adds PP data service functions to `/previous-sin`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> update /previous-sin to use PP data service functions

- frontend/app/routes/protected/person-case/review.tsx
Trivial fixup of types in `review.tsx`.
> refactor(frontend): clean up types in `review.tsx`

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/person-case/primary-docs.tsx
Cleans up unused locales since using the PP data service functions.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide …
> cleanup unused locales

- frontend/app/routes/protected/person-case/personal-info.tsx
Fix the console error.
On adding first name previously used and pressing add name button, a console error is logged: "A component is changing an uncontrolled input to be controlled." This is caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
> update(frontend): fix console error on personal detail screen

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/data-table.tsx
- frontend/app/routes/protected/multi-channel/search-sin.tsx
Updates `/search-sin` to include more realistic fake data in the UI, and updates `<DataTable />` with a more sensible type system (IMO)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> update /search-sin and DataTable component

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/page-details.tsx
- frontend/app/components/page-title.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/layout.tsx
- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
- frontend/app/utils/date-utils.ts
- frontend/tests/components/__snapshots__/page-details.test.tsx.snap
[AB#14699](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/14699) Create Confirmation Page
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend): sin confirmation screen

- infrastructure/terragrunt/nonprod/frontend-service-principal/terragrunt.hcl
In preparation for new int pseudoenvironment, this PR adds the correct OIDC callback to our infrastructure project.
> feat(infra): add new int oidc callback

- gitops/overlays/int/configs/future-sir-frontend/config.conf
- gitops/overlays/int/external-secrets.yaml
- gitops/overlays/int/ingresses.yaml
- gitops/overlays/int/kustomization.yaml
- gitops/overlays/int/patches/deployments.yaml
This PR creates a new `int` pseudoenvironment that will always have the latest build deployed. (TC jobs to be updated once this is merged)
> feat(gitops): create new `int` pseudoenvironment

- gitops/overlays/dev/configs/future-sir-frontend/config.conf
Trivial PR to bring the dev `config.conf` file in line with our base `.env.example` file.
> refactor(gitops): update dev config

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
[AB#18733](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18733)
Adds a very basic implementation for `/multi-channel/finalize-request`.  Future work is marked by todos.
- [] 🛠️ **refactoring** -- non-breaking change that improves code readability or structure
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
npm run …
```
> add /multi-channel/finalize-request route with naive implementation

- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
Add Abandon button (with functionality) on all screen inside in-person flow.
Removed Progress bar to make it consistent with design in figma.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend): abandon button on all screens

- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
[AB18740](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18740) Create printable SIN letter
SIN is hidden until the "Print" button is clicked
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend): Printable SIN letter

- frontend/app/components/address.tsx
Trivial fixup of `<Address>` types.
> refactor(frontend): fixup `<Address>` types

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/app/routes/protected/person-case/review.tsx
Rename "Next" button on review screen to "Create case" to match design in figma.
Removed un-used values from locale files.
fix the checkbox input on finalize request on multi-channel route.
> refactor(frontend): rename next button to create case on review screen

- frontend/.env.example
- frontend/app/.server/environment/interop-api.ts
- frontend/app/.server/environment/server.ts
- frontend/app/.server/shared/api/interop-client-config.ts
This PR adds support for Interop API environment variables and updates the generated client code to use them.
> feat(frontend): add interop-api environment variable support

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/contextual-alert.tsx
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
Adds `<ContextualAlert />` which is needed in parts of the application.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide …
> add contextual alert component

- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/app/utils/i18n-utils.ts
- frontend/tests/utils/i18n-utils.test.ts
[AB18963](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18963) Refactor validation errors
Validation refactored to return error keys rather than pre-translated strings
> refactor(frontend): Refactor validation errors

- frontend/.env.example
- frontend/app/.server/environment/interop-api.ts
- frontend/app/.server/shared/api/interop-client-config.ts
- gitops/overlays/int/configs/future-sir-frontend/config.conf
> refactor(gitops): update Interop API configuration in int/config.conf

- frontend/.env.example
- frontend/app/.server/environment/client.ts
- frontend/app/.server/shared/services/province-service.ts
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
Makes `RC_CODES` configurable as an env var (debatable if this is needed though?) and updates `multi-channel/finalize-request` to display the RC_CODES as `${provinceName} - ${RC_CODE}` per figma.  
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide …
> refactor RC_CODES for display in /multi-channel/finalize-request

- frontend/app/routes/protected/person-case/validation.server.ts
I tested this with some console logs and it does appear that `v.lazy` lazy loads as expected.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> lazy load service function calls in validation.server.ts

- frontend/app/routes/protected/person-case/current-name.tsx
Update the Boolean checks in current name screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or …
> refactor(frontend): update the Boolean checks in current name screen

- frontend/app/routes/protected/person-case/current-name.tsx
fix syntax error on current name to fix build fail
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or …
> (frontend): fix syntax error on current name to fix build fail

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/person-case/privacy-statement.tsx
Replaces lorum ipsum with figma content.  Also deciding not to spend the extra 10 minutes to translate this with google translate since I guarantee the figma content will change.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary …
> update content in /privacy-statement

- frontend/tsconfig.json
Enable `erasableSyntaxOnly` TS flag avaiable since Typescript v5.8.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-8.html#the---erasablesyntaxonly-option
> build(frontend): enable erasableSyntaxOnly TS flag

- gitops/overlays/int/configs/future-sir-frontend/config.conf
- gitops/overlays/int/external-secrets.yaml
> fix(gitops): reconfigure int environment

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/components/contextual-alert.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/sin-application.tsx
[AB18962](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18962)
- Created Summary and Send for validation screen
- Refactored `review.tsx` by relocating application information to `frontend/app/routes/protected/sin-application.tsx`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant …
> feat(frontend): Send for validation screen

- gitops/overlays/int/external-secrets.yaml
Made a mistake in #396. Also minor refactoring.
> fix(gitops): reconfigure int env

- frontend/app/domain/constants.ts
- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/validation.server.ts
- frontend/app/routes/protected/sin-application.tsx
change the data source for current status in Canada on primary doc screen and review screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): change the data source for current status in Canada on primary doc

- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/state-machine.server.ts
- frontend/app/routes/protected/person-case/types.d.ts
[AB#19081](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19081)
This PR adds a proof-of-concept for persisting error messages and form values when a user toggles the language of the page.  Things to notice: error messages should persist once the language is toggled, default form values should also persist (this is only if the user has previously submitted the form to trigger form validation).
<details>
``` shell …
```
> POC implementation of persistent raw form data and error validation on language toggle

- frontend/app/.server/resources/fsir_applicantsupportingdocumenttypes.json
[AB19274](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19274)
Add a custom FSIR data resource: fsir_applicantsupportingdocumenttypes.json. 
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> add custom fsir data resource for supporting document

- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/layout.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/eslint.config.mjs
Fix strict equality (===) and strict inequality (!==). Add [eqeqeq](https://eslint.org/docs/latest/rules/eqeqeq) eslint rule to tract these future issues.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to …
> fix(frontend): strict equality and inequality

- frontend/app/.server/validation/string-to-integer-schema.ts
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/state-machine.server.ts
- frontend/app/routes/protected/person-case/validation.server.ts
Fixed regression that was introduced during previous refactoring (#403).
> fix(frontend): state machine regression (setFormData)

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/app/routes/protected/multi-channel/pid-verification.tsx
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/sin-application.tsx
Clean up some types, todos, locales, and actions that were missing in the multi-channel flow.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> minor fixes to multi-channel flow

- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/app/routes/protected/person-case/validation.server.ts
Update validation on the secondary-docs page to match Frank's solution used in primary-docs. Also minor refactoring to enhance readability.
> fix(frontend): update validation

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/.server/resources/fsir_applicantsupportingdocumenttypes.json
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/validation.server.ts
- frontend/app/routes/protected/sin-application.tsx
[AB#19276](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19276)
changed data source for supporting document types on name of SIN and review screens
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to …
> refactor(frontend): changed data source for supporting document types on name of SIN

- frontend/containerfile
Add convenience-comment to `containerfile` that shows how to check for image updates using podman.
> docs(frontend): add instructions for checking base image updates

- frontend/app/entry.server.tsx
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/package-lock.json
- frontend/package.json
Remove unused `@valibot/i18n` package.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to …
> chore(frontend): remove @valibot/i18n package

- frontend/app/.server/domain/sin-application/sin-application-service-default.ts
- frontend/app/.server/domain/sin-application/sin-application-service-mock.ts
- frontend/app/.server/domain/sin-application/sin-application-service.ts
- frontend/app/.server/environment/features.ts
- frontend/app/routes/protected/person-case/review.tsx
- frontend/tests/.server/domain/sin-application/sin-application-service-default.test.ts
- frontend/tests/.server/domain/sin-application/sin-application-service-mock.test.ts
- frontend/tests/.server/domain/sin-application/sin-application-service.test.ts
Implement SIN application service mocking. The mock service will be used when the `ENABLE_SIN_APPLICATION_SERVICE_MOCK` environment variable is set to `true`; otherwise, the default service will be used. By default, `ENABLE_SIN_APPLICATION_SERVICE_MOCK` is set to `"false"` in production (`NODE_ENV === "production"`) and `"true"` for local development.
[AB#18736](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18736)
<details>
<summary>Linting and …
> feat(frontend): sin application service mocking

- frontend/.env.example
- gitops/base/future-sir-frontend/configs/config.conf
- gitops/overlays/dev/configs/future-sir-frontend/config.conf
- gitops/overlays/int/configs/future-sir-frontend/config.conf
Set the `ENABLE_SIN_APPLICATION_SERVICE_MOCK` configuration for ops:  
- **DEV:** true  
- **INT:** [empty]
Fixes [AB#18736](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18736)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your …
> ops: ENABLE_SIN_APPLICATION_SERVICE_MOCK config

- frontend/app/.server/utils/auth-utils.ts
- frontend/app/routes/protected/admin.tsx
- frontend/app/routes/protected/index.tsx
- frontend/app/routes/protected/layout.tsx
- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/app/routes/protected/multi-channel/pid-verification.tsx
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
- frontend/app/routes/protected/person-case/abandon.tsx
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/app/routes/protected/request.tsx
This is an incremental PR that will ultimately finish with full integration with AWS Cognito. 
This PR renames the `requireAuth()` function in `~/.server/utils/auth-utils.ts` to `requireAllRoles()` so I can eventually add a new `requireAnyRole()` function.
> refactor(auth): rename requireAuth to requireAllRoles for RBAC

- frontend/app/.server/utils/auth-utils.ts
This is an incremental PR that will ultimately finish with full integration with AWS Cognito.
This PR add a `requireAnyRole()` function to `~/.server/utils/auth-utils.ts`.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
To keep this PR small, No tests were created. Since no existing `auth-utils.test.ts` file exists, …
> feat(frontend): add `requireAnyRole()` function for RBAC

- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/state-machine-models.ts
As stated in the title, make properties optional with `?: undefined` instead of omitting them in a type intersection. Omitting them makes it difficult to determine which properties exist without performing a type assertion to obtain the correct intersection.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR …
> refactor(frontend): relax person-case machine CurrentNameData model intersection

- frontend/.env.example
- frontend/app/.server/environment/authentication.ts
Reverts DTS-STN/future-sir#447 (we will take a different approach for our prototype)
> Revert "feat(frontend): add AWS Cognito configuration options to environment"

- frontend/app/.server/auth/auth-strategies.ts
- frontend/tests/auth/auth-strategies.test.ts
Reverts DTS-STN/future-sir#446 (we will take a different approach for our prototype).
> Revert "feat(frontend): add AWS Cognito authentication strategy"

- frontend/.env.example
- frontend/app/.server/domain/multi-channel/services/case-api-service.ts
- frontend/app/.server/environment/features.ts
[AB#19348](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19348)
Adds `enabled-mocks` to the server environment. Not sure if the default makes sense, I'm sure one of you will point out any flaws.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, …
> add enabled_mocks env var for person sin case mock api

- frontend/app/components/date-picker-field.tsx
- frontend/tests/components/__snapshots__/date-picker-field.test.tsx.snap
As stated in title, fixing regression introduced in #454 
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> fix(frontend): Ensure DatePickerField shows an unselected month option when defaultValue is undefined

- frontend/app/.server/domain/multi-channel/mocks/case-api-service.mock.ts
- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/.server/resources/fsir_applicantprimarydocumentchoices.json
- frontend/app/domain/constants.ts
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/validation.server.ts
- frontend/app/routes/protected/sin-application.tsx
- frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts
Change data source for doc type on primary doc screen and review screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): change data source for doc type on primary doc screen and review screen

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
cleanup locales, merge multiple occurrence of Select options at one place.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide …
> refactor(frontend): cleanup locales, merge multiple occurrence of Select options at one place

- frontend/app/.server/domain/multi-channel/case-api-service-default.ts
- frontend/app/.server/domain/multi-channel/case-api-service-mock.ts
- frontend/app/.server/domain/multi-channel/case-api-service-models.ts
- frontend/app/.server/domain/multi-channel/case-api-service.ts
- frontend/app/routes/protected/multi-channel/send-validation.tsx
Restructures the `case-api-service` to follow the established convention seen in the `sin-application-service`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> modify case-api-service to follow established convention

- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
This might be overkill or even moot, but currently the DOM displays the SIN (in the developer console).  It's currently hidden with CSS.  This PR introduces JS to control displaying the SIN only when the print button is clicked.  Note: using ctrl-p in the browser will not fire the same functionality for displaying the SIN on print.  Yes, there are browser events (`beforeprint`, `afterprint`) that could maybe have event listeners attached to them.  I tried, but couldn't get them fire.   …
> modify print in /multi-channel/sin-confirmation

- frontend/app/routes/protected/person-case/abandon.tsx
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/current-name.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/person-case/route-helpers.server.ts
- frontend/app/routes/protected/person-case/secondary-doc.tsx
- frontend/app/routes/protected/person-case/state-machine.server.ts
- frontend/tests/routes/protected/person-case/route-helpers.server.test.ts
This PR introduces the `getTabIdOrRedirect` and `loadMachineContextOrRedirect` functions to standardize loading the machine actor and tab ID across person case routes. It centralizes state management and ensures consistent redirection if required data is missing.
- Added `getTabIdOrRedirect` to extract `tabId`.
- Added `loadMachineContextOrRedirect` to load `machineActor`.
- Integrated the functions in person case route loaders and actions.
- Improved logging for missing `tabId` or `machineActor`.
- Consistent approach for loading machine context.
- Reduces errors and improves debugging.
Before submitting this PR, ensure that you have completed the following. You can fill these …
> feat(frontend): person case route helpers

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
Code cleanup- removed unused values from "protected" locales
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): code cleanup - remove unused values from locales

- frontend/app/routes/protected/person-case/request-details.tsx
Fix UI issues:
- Set `required` prop on `Type of request` select input.
- Remove `rounded-sm` class on `Type of request` select input.
- Disable `select-option` option on `Type of request` select input.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and …
> fix(frontend): request-details UI issues

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
Code cleanup, remove unused values from "gcweb" locales
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> refactor(frontend): code cleanup remove unused values from gcweb locales

- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
…n mapper
[AB#](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19552)
update the hard coded value for previous SIN with environment variable on SIN application mapper
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. …
> refactor(frontend): update the value for previous SIN with env variable on SIN application mapper

- frontend/.env.example
- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/app/.server/environment/client.ts
Updated the hard coded value for applicants status in Canada on SIN application mapper
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to …
> refactor(frontend): update the hard coded value for applicants status in Canada

- frontend/app/routes/protected/person-case/current-name.tsx
As per title.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
> style(frontend): review and fix current name route style

- frontend/.env.example
- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/app/.server/environment/client.ts
- frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts
…ication request
update the hard coded value for the primary document type on SIN application request
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. …
> refactor(frontend): update the hard coded value for the primary document type on SIN application request

- frontend/.env.example
- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/app/.server/environment/client.ts
[AB#](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19552)
update the hard coded value for the SIN Confirmation receiving method on SIN Application mapper
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free …
> refactor(frontend): update the hard coded value for the SIN Confirmation receiving method on SIN Application mapper

- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/personal-info.tsx
- frontend/app/routes/protected/person-case/previous-sin.tsx
- frontend/app/routes/protected/person-case/privacy-statement.tsx
- frontend/app/routes/protected/person-case/review.tsx
- frontend/app/routes/protected/sin-application/review-personal-info.tsx
Makes consistent use of `max-w-prose` blocks in the person-case flow.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide …
> modify styles to use consitent max-w-prose

- frontend/app/routes/protected/person-case/primary-docs.tsx
- frontend/app/routes/protected/person-case/state-machine-models.ts
- frontend/app/routes/protected/person-case/validation.server.ts
- frontend/app/routes/protected/sin-application/primary-docs-form.tsx
- frontend/app/routes/protected/sin-application/validation.server.ts
Move primary-docs form to separate component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
This PR is to prepare for editing the sin-application in the multi-channel flow. Implementing a portion of the changes seen in the draft PR https://github.com/DTS-STN/future-sir/pull/437.
Provide screenshots or screen-recordings to …
> refactor(frontend): move primary-docs form to separate component

- frontend/app/routes/protected/sin-application/primary-docs-form.tsx
Per title.  Keeps the structure and styling consistent.  I believe this was accidentally removed on refactoring 
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> re-add max-w-prose to /primary-docs

- frontend/app/.server/domain/multi-channel/sin-cases-store.ts
- frontend/app/.server/utils/instance-registry.ts
Minor refactor to use the `singleton()` function to initialize `sinCasesStore`.
> refactor(frontend): implement singleton pattern for sinCasesStore

- frontend/app/.server/domain/multi-channel/case-api-service-default.ts
- frontend/app/.server/domain/multi-channel/case-api-service-mock.ts
- frontend/app/.server/domain/multi-channel/case-api-service.ts
- frontend/app/.server/domain/multi-channel/sin-cases-store-default.ts
- frontend/app/.server/domain/multi-channel/sin-cases-store-redis.ts
- frontend/app/.server/domain/multi-channel/sin-cases-store.ts
- frontend/app/errors/error-codes.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- frontend/app/routes/protected/multi-channel/send-validation.tsx
Refactor sin cases stores and case api services methods to follow CDCP [Method Naming Conventions (Repository and Service)](https://github.com/DTS-STN/canadian-dental-care-plan/tree/main/frontend#method-naming-conventions-repository-and-service).
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces …
> refactor(frontend): sin cases stores and case api services methods

- gitops/overlays/dev/configs/future-sir-frontend/config.conf
- gitops/overlays/int/configs/future-sir-frontend/config.conf
per title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(gitops) add INTEROP_SIN_SEARCH_API_BASE_URL to dev and int configs

- frontend/app/routes/protected/multi-channel/search-sin.tsx
per title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend) extract caseId from path params and use in service call

- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/app/routes/protected/multi-channel/pid-verification.tsx
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- frontend/app/routes/protected/multi-channel/send-validation.tsx
- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
find sin case using caseId params in each loaders and actions of multi-channel route
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): find sin case using caseId params in each loaders and actions of multi-channel route

- frontend/app/@types/express-session.d.ts
> refactor(frontend): remove unused PersonSinCase type from session data

- frontend/app/routes/protected/person-case/contact-information.tsx
[AB#19763](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19763)
Reorder address fields on contact information screen sequencing: Country → Address → City → Province → Postal Code.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary …
> refactor(frontend): reorder address fields on contact information screen

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/layout.tsx
Minor tweak to the appbar menu.. see screenshot below.
> refactor(frontend): update portal navigation labels in protected locales

- frontend/app/.server/domain/multi-channel/search-api-service-default.ts
- frontend/app/.server/environment/server.ts
Redact the AWS ID token since there's no value in logging in (in my opinion).
> refactor(frontend) update `TMP_AWS_ID_TOKEN` to apply Redacted transformation

- frontend/app/.server/domain/multi-channel/search-api-faker.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
The returned search score in the hitlist results are out of 10, meaning we need to transform before displaying in the table.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, …
> refactor(frontend) modify search score logic

- infrastructure/terragrunt/nonprod/frontend-service-principal/terragrunt.hcl
Update security roles and groups for nonprod.
> fix(infra): add missing role assignments for frontend service principal

- frontend/app/routes/protected/person-case/validation.server.ts
[AB#19760](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19760) Fix Expiry Date Validation
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> fix(frontend): fix expiry date validation

- frontend/app/routes/protected/multi-channel/finalize-request.tsx
- frontend/app/routes/protected/person-case/birth-details.tsx
- frontend/app/routes/protected/person-case/contact-information.tsx
- frontend/app/routes/protected/person-case/parent-details.tsx
- frontend/app/routes/protected/person-case/request-details.tsx
Ensure Consistent Styling Across All Routes.
Fixes [AB#19769](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19769)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to …
> style(frontend): Ensure consistent styling across all routes

- frontend/.env.example
- frontend/app/.server/domain/multi-channel/search-api-service-default.ts
- frontend/app/.server/environment/interop-api.ts
Add a separate auth header config entry for the SIN search endpoint.
Gitops config updates will be handled in another PR.
> fix(frontend): update Interop API configuration

- frontend/app/routes/protected/person-case/previous-sin.tsx
This field is required
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers …
> fix(frontend) add required to sin field

- gitops/base/future-sir-frontend/configs/config.conf
- gitops/overlays/dev/configs/future-sir-frontend/config.conf
- gitops/overlays/int/configs/future-sir-frontend/config.conf
- gitops/overlays/int/external-secrets.yaml
Fixup gitops configs to align with the changes in #512.
Also sync the .conf files with our base `.env.example` file.
> fix(gitops): fixup gitops .conf files

- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/app/.server/domain/sin-application/sin-application-service-default.ts
- frontend/app/.server/domain/sin-application/sin-application-service-mock.ts
- frontend/app/.server/domain/sin-application/sin-application-service.ts
- frontend/app/routes/protected/person-case/review.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts
- frontend/tests/.server/domain/sin-application/sin-application-service-default.test.ts
- frontend/tests/.server/domain/sin-application/sin-application-service-mock.test.ts
As per title.
[AB#19771](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/19771)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> feat(frontend): add user ID token to submit SIN application payload

- frontend/.env.example
Adds missing env var
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers …
> feat(frontend) update env.example with ENABLE_ASSOCIATE_SIN_SERVICE_MOCK

- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts
[AB#18736](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/18736)
update country and province data on SIN application request
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): update country and province data on SIN application request

- gitops/base/future-sir-frontend/configs/config.conf
- gitops/overlays/dev/configs/future-sir-frontend/config.conf
- gitops/overlays/int/configs/future-sir-frontend/config.conf
- gitops/overlays/int/external-secrets.yaml
[AB#18738](https://dev.azure.com/ESDCCM/a4b4f7af-bbd7-4f0d-83ab-a123d0b70fda/_workitems/edit/18738)
per title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(gitops) update configs for associate sin service

- frontend/app/routes/protected/multi-channel/search-sin.tsx
Uses the found personSinCase to populate tombstone data about the applicant in the UI.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend) use found personSinCase in search-sin

- frontend/app/routes/protected/multi-channel/finalize-request.tsx
Use personSinCase to conditionally render a block of content in the UI if the applicant is from multiple births
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend) use personSinCase in finalize-request

- frontend/app/routes/protected/multi-channel/sin-confirmation.tsx
Use personSinCase on /sin-confirmation to display information about the applicant in the UI
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> feat(frontend) use personSinCase on sin-confirmation

- frontend/app/.server/locales/protected-en.json
- frontend/app/.server/locales/protected-fr.json
- frontend/app/routes/protected/person-case/validation.server.ts
- frontend/app/routes/protected/sin-application/validation.server.ts
[AB#19852](https://dev.azure.com/ESDCCM/FSIR/_workitems/edit/19852)
update validation on citizenship date on primary identification screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): update validation on citizenship date on primary identification screen

- frontend/app/.server/domain/sin-application/sin-application-mappers.ts
- frontend/tests/.server/domain/sin-application/sin-application-mappers.test.ts
update the SIN response as the SINApplicationIdentification is an array.
TODO: update test
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> refactor(frontend): update the SIN response

- gitops/overlays/int/configs/future-sir-frontend/config.conf
The app errors because we post to the wrong endpoint when calling the associate-sin service.  
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> fix(gitops) modify INTEROP_ASSOCIATE_SIN_API_BASE_URL in int config

- frontend/app/.server/domain/multi-channel/search-api-faker.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- Result scores are always integers. 
- PP results randomly return 'error-ful' data (by design).  These need to be filtered out before rendering in the UI
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces …
> fix(frontend) modify search-sin to account for potential errors in returned PP search results

- frontend/app/.server/domain/multi-channel/search-api-faker.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
Removes sorting from the mock and adds it to the route since PP doesn't sort the result data by score.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and …
> fix(frontend) modify search-sin to sort by score and render name properly

- frontend/app/.server/domain/multi-channel/search-api-service-default.ts
- frontend/app/.server/domain/multi-channel/search-api-service-mock.ts
Adds logging to search-sin service
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
> fix(frontend) add logging for search-sin service

- frontend/app/.server/domain/multi-channel/associate-sin-service-default.ts
- frontend/app/.server/domain/multi-channel/associate-sin-service-mock.ts
- frontend/app/.server/domain/multi-channel/search-api-service-default.ts
- frontend/app/.server/domain/multi-channel/search-api-service-mock.ts
per title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the …
> fix(frontend) update logging in sin-search and associate-sin services

- frontend/app/.server/locales/gcweb-en.json
- frontend/app/.server/locales/gcweb-fr.json
- frontend/app/@types/@tanstack-table.types.ts
- frontend/app/components/button.tsx
- frontend/app/components/data-table.tsx
- frontend/app/domain/constants.ts
- frontend/app/routes/protected/multi-channel/search-sin.tsx
- frontend/package-lock.json
- frontend/package.json
Update DataTable components to align with the [Shadcn DataTable](https://ui.shadcn.com/docs/components/data-table) using [TanStack Table](https://tanstack.com/table/v8/docs/introduction). This update introduces pagination via the `DataTablePagination` component and column sorting through the `DataTableColumnHeader` component. Additionally, the SIN search functionality has been updated to leverage this new implementation, and localization has been applied.
<details>
<summary>Linting and …
> feat(frontend): TanStack Table

- frontend/app/i18n-routes.ts
Just a small addition to the i18n route types that can be useful in the future.
> feat(frontend): add utility types to extract ids from i18n routes

- frontend/app/.server/auth/auth-strategies.ts
> docs(frontend): update jsdoc in `BaseAuthenticationStrategy`

- frontend/app/.server/utils/security-utils.ts
> fix(frontend): add return type to `make` method in `Redacted` class

- gitops/base/future-sir-frontend/configs/config.conf
- gitops/base/future-sir-frontend/deployments.yaml
- gitops/overlays/dev/configs/future-sir-frontend/config.conf
- gitops/overlays/int/configs/future-sir-frontend/config.conf
- update the deployment's resource limits to better match the usage being reported by Dynatrace
- sync `.conf` files with our `.env.example` file
> chore(gitops): update configuration files

- gitops/base/redis/stateful-sets.yaml
> fix(gitops): optimize Redis stateful set resource limits and probe timeouts

- gitops/base/redis/stateful-sets.yaml
> chore(gitops): update resource requests and limits for redis containers

- frontend/eslint.config.mjs
All of the eslint plugins we use have been updated to support the new eslint configuration format. This PR migrates the config to those new settings.
> refactor(frontend): update eslint rules to remove compat calls
